import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { HomePage } from '../src/components/home/home-page';
import { Header } from '../src/components/header/header';
import { Footer } from '../src/components/footer/footer';


export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage data={data}/>
    </div>
  )
}

export async function getServerSideProps(){
  //runs on server side - renders before home component 
  const {events_categories} = await import('/data/data.json');
  return {
      props:{
          data: events_categories,
      },
  };
}